image: nikolaik/python-nodejs:python3.11-nodejs20


stages:
  - build
  - test

build:
  stage: build
  script:
  - pip install -e .
  - npm install -g remark-cli
  - npm install -g remark-directive

test:
  stage: test
  script:
  - pytest -v -s .
